### ISSUE TITLE
Server Crash - Feature Replacement

### ISSUE THREAD

**Issue by Crix310** [Melonslise/Subterranean-Wilderness#22]
Hello! I was playing Minecraft with my friends and while we were exploring the server suddenly crashed and when we try to open it and join the world the server crashes again. After checking the various crash reports, I found that the problem is caused by a problem with Subterranean Wilderness, but I'm not really sure about that. Check it out by yourself.

Here's the crash log: https://pastebin.com/c1NsJiep

Hope to have an answer as soon as possible.

**Comment by PaintNinja** [comment]
You’re using an outdated version of the mod (v1.1.1 according to your logs).

Please only download the mod from CurseForge if you found it elsewhere and make sure that you have the latest version before reporting an issue, as this was fixed in v1.1.2 ;)

https://www.curseforge.com/minecraft/mc-mods/subterranean-wilderness/files/3178364
